In [1]:
import sys
import os
import pandas as pd
import plotly.express as px
import ast
from sklearn.preprocessing import StandardScaler, MinMaxScaler

sys.path.append(os.path.abspath('../src/'))
from ActivationFunction import *
import PlotUtils
from MatrixNeuralNetwork import *

In [2]:
RANDOM_STATE = 310907

tr_norm_df = pd.read_csv('../data/divided_std_train_0_8.csv')
test_norm_df = pd.read_csv('../data/divided_std_test_0_2.csv')

tr_df = pd.read_csv('../data/divided_train_0_8.csv')
test_df = pd.read_csv('../data/divided_test_0_2.csv')

TR_INPUT = 10
TR_OUTPUT = 3

tr_normalized = tr_norm_df.values
test_normalized = test_norm_df.values
training_set = tr_df.values
test_set = test_df.values

scaler_out = StandardScaler()
scaler_out.fit(training_set[:,TR_INPUT:])

training_len = len(tr_norm_df)
test_len = len(test_norm_df)

In [3]:
tr_normalized.shape

(800, 13)

In [4]:
complex_struct = [[10, SigmoidFunction(2), ['uniform', {'low':-1, 'high':1}]],
          [15, RectifiedLinearUnit(), ['uniform', {'low':0, 'high':1}]],
          [25, HyperbolicTangentFunction(4), ['uniform', {'low':-1, 'high':1}]],
          [50, ExponentialLinearUnit(), ['uniform', {'low':0, 'high':1}]],
          [500, SigmoidFunction(8), ['uniform', {'low':-1, 'high':1}]],
          [3, IdentityFunction(), ['uniform', {'low':-1, 'high':1}]]]
simple_struct = [[5, ExponentialLinearUnit(), ['uniform', {'low':1, 'high':1}]],
          [5, ExponentialLinearUnit(), ['uniform', {'low':1, 'high':2}]],
          [1, IdentityFunction(), ['uniform', {'low':1, 'high':1}]]]

myNN = MatrixNeuralNetwork(simple_struct, 3, RANDOM_STATE)
print(myNN)

layer_0
ExponentialLinearUnit : (3, 5)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----------------------------------------------------------------------------------------------------
layer_1
ExponentialLinearUnit : (5, 5)
[[1.70396911 1.81308644 1.07900086 1.46460136 1.22871116]
 [1.43378991 1.48900104 1.66435727 1.0086825  1.89593504]
 [1.80643407 1.79429515 1.57725673 1.00701088 1.44145726]
 [1.81104907 1.22822733 1.89264228 1.49618163 1.97660795]
 [1.64448865 1.47825453 1.04906616 1.51198158 1.17642728]]
----------------------------------------------------------------------------------------------------
layer_2
IdentityFunction : (5, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
----------------------------------------------------------------------------------------------------



In [15]:
tr_normalized[[8]][:3]

array([[ 0.9008453 , -1.34720733,  1.12962203, -0.27994833,  0.56496437,
         0.93743131, -0.57698413, -1.91691909, -1.05582719,  1.31763302,
         0.67092711, -2.15171377,  1.09496363]])

In [16]:
def circular_index(a, start, stop): 
            '''
            start is included
            stop is NOT included
            '''
            # fn to convert your start stop to a wrapped range
            if stop<=start:
                stop += len(a)
            return np.arange(start, stop)%len(a)

In [31]:
len(tr_normalized)

800

array([[ 1.42583762,  0.85067755,  1.27668474],
       [-0.94887093,  0.85024236, -0.7990482 ],
       [-0.84677264, -1.19199602, -0.73974572],
       [ 0.9008453 , -1.34720733,  1.12962203],
       [ 0.98870128, -1.33901788,  1.51646761]])

In [44]:
import time
start_time = time.time()

k = 0
step = 33
tot_len = 800
for i in range(1000000):
    a = tr_normalized[circular_index(tr_normalized, k, (k+step)%tot_len)][:,:10]
    k = (k+step)%tot_len

print("--- %s seconds ---" % (time.time() - start_time))

start_time = time.time()
for i in range(1000000):
    high = max(k+step, (k+step)%tot_len)
    a = tr_normalized[k:high,:10]
    k = (k+step)%tot_len

print("--- %s seconds ---" % (time.time() - start_time))

--- 4.591940879821777 seconds ---
--- 0.537449836730957 seconds ---


In [6]:
myNN.predict(tr_normalized[:10, :3])

array([[ -4.91791387],
       [ -4.99057537],
       [133.82025028],
       [ -2.76932294],
       [ 33.75574801],
       [133.85797797],
       [ -4.93802718],
       [ -4.99486238],
       [ 25.74012277],
       [ 43.93184144]])