In [1]:
import sys
import os
import pandas as pd
import plotly.express as px
import ast
from sklearn.preprocessing import StandardScaler, MinMaxScaler

sys.path.append(os.path.abspath('../src/'))
from ActivationFunction import *
import PlotUtils
from MatrixNeuralNetwork import *

In [2]:
RANDOM_STATE = 310907

tr_norm_df = pd.read_csv('../data/divided_std_train_0_8.csv')
test_norm_df = pd.read_csv('../data/divided_std_test_0_2.csv')

tr_df = pd.read_csv('../data/divided_train_0_8.csv')
test_df = pd.read_csv('../data/divided_test_0_2.csv')

TR_INPUT = 10
TR_OUTPUT = 3

tr_normalized = tr_norm_df.values
test_normalized = test_norm_df.values
training_set = tr_df.values
test_set = test_df.values

scaler_out = StandardScaler()
scaler_out.fit(training_set[:,TR_INPUT:])

training_len = len(tr_norm_df)
test_len = len(test_norm_df)

In [3]:
tr_normalized.shape

(800, 13)

In [4]:
complex_struct = [[10, SigmoidFunction(2), ['uniform', {'low':-1, 'high':1}]],
          [15, RectifiedLinearUnit(), ['uniform', {'low':0, 'high':1}]],
          [25, HyperbolicTangentFunction(4), ['uniform', {'low':-1, 'high':1}]],
          [50, ExponentialLinearUnit(), ['uniform', {'low':0, 'high':1}]],
          [500, SigmoidFunction(8), ['uniform', {'low':-1, 'high':1}]],
          [3, IdentityFunction(), ['uniform', {'low':-1, 'high':1}]]]
simple_struct = [[5, ExponentialLinearUnit(), ['uniform', {'low':0.5, 'high':0.5}]],
          [5, ExponentialLinearUnit(), ['uniform', {'low':0, 'high':0.75}]],
          [2, IdentityFunction(), ['uniform', {'low':-0.7, 'high':0.7}]]]

myNN = MatrixNeuralNetwork(simple_struct, 3, RANDOM_STATE)
print(myNN)

layer_0
ExponentialLinearUnit : (4, 5)
[[0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5]]
----------------------------------------------------------------------------------------------------
layer_1
ExponentialLinearUnit : (6, 5)
[[0.32534243 0.36675078 0.49826795 0.00651187 0.67195128]
 [0.60482555 0.59572137 0.43294254 0.00525816 0.33109295]
 [0.60828681 0.17117049 0.66948171 0.37213622 0.73245596]
 [0.48336649 0.3586909  0.03679962 0.38398619 0.13232046]
 [0.45193295 0.54799595 0.5734715  0.11392521 0.5275575 ]
 [0.72746016 0.53238461 0.07829251 0.36764233 0.22830986]]
----------------------------------------------------------------------------------------------------
layer_2
IdentityFunction : (6, 2)
[[-0.57713659  0.50576502]
 [ 0.01011749  0.45104315]
 [ 0.09605322  0.17393659]
 [-0.44277123  0.47437927]
 [ 0.09600984 -0.05205604]
 [ 0.36405442  0.45305754]]
---------------------------------------------------------------------------------

In [10]:
myNN.predict_for_training(tr_normalized[:10, :3])

[[ 0.09635145  0.09635145  0.09635145  0.09635145  0.09635145]
 [-0.45888473 -0.45888473 -0.45888473 -0.45888473 -0.45888473]
 [ 2.27609923  2.27609923  2.27609923  2.27609923  2.27609923]
 [ 0.44317069  0.44317069  0.44317069  0.44317069  0.44317069]
 [ 0.94801559  0.94801559  0.94801559  0.94801559  0.94801559]
 [ 2.27659996  2.27659996  2.27659996  2.27659996  2.27659996]
 [ 0.05116161  0.05116161  0.05116161  0.05116161  0.05116161]
 [-0.88925719 -0.88925719 -0.88925719 -0.88925719 -0.88925719]
 [ 0.84163     0.84163     0.84163     0.84163     0.84163   ]
 [ 1.0830755   1.0830755   1.0830755   1.0830755   1.0830755 ]]
----------------
[[ 0.96580996  0.72897331  0.29132202  0.45260673  0.45910801]
 [-0.18291086 -0.21848094 -0.73536833  0.04312293 -0.65321783]
 [ 6.35797023  5.17637699  5.11066443  2.3747468   5.6804282 ]
 [ 1.82375552  1.43659883  1.05812665  0.75843806  1.28987124]
 [ 3.07261772  2.46664877  2.1743202   1.2036192   2.49916568]
 [ 6.35920892  5.17739865  5.11177153

array([[-0.31431439,  1.51180832],
       [ 0.34338646,  0.23485338],
       [-3.26818763,  7.72322746],
       [-0.78430458,  2.500106  ],
       [-1.46844238,  3.93871431],
       [-3.26886619,  7.72465435],
       [-0.25307564,  1.38303518],
       [ 0.58599339, -0.1825041 ],
       [-1.32427453,  3.63555746],
       [-1.65146808,  4.32358166]])

In [11]:
myNN.backpropagate(tr_normalized[:10, -1:])

[[-0.9327713  -1.42938033 -1.36130145 -1.19146627 -1.3978347 ]
 [ 0.0531673   0.08229469  0.07900203  0.06965062  0.08013494]
 [-3.39903063 -6.00968546 -6.33506656 -6.03723809 -5.54188274]
 [-0.66527418 -1.38552076 -1.59903298 -1.6246215  -1.2017718 ]
 [-1.28136403 -2.49890627 -2.78865095 -2.76991729 -2.21974854]
 [-3.20092637 -5.77812892 -6.16952898 -5.93663657 -5.28530102]
 [-1.02677163 -1.50434475 -1.37994764 -1.16530838 -1.50005129]
 [ 0.05152085  0.2022565   0.28677424  0.3268161   0.14619675]
 [-1.1578706  -2.27170022 -2.54327833 -2.5318132  -2.01344266]
 [-2.18640052 -3.66343024 -3.72792994 -3.45528802 -3.45161447]]
----------------
[[-8.70624744e-01 -1.16588366e+00 -5.17986776e-01 -8.89730840e-01
   6.24429658e-02]
 [ 5.22668579e-02  6.59167476e-02  2.88093615e-02  5.26485373e-02
  -4.03297652e-03]
 [-5.75002100e+00 -3.72381194e+00 -1.18947770e+00 -5.12953525e+00
   6.89763686e-01]
 [-1.79882704e+00 -5.91758992e-01 -5.04260681e-02 -1.49707938e+00
   2.55767254e-01]
 [-2.9186011

In [7]:
import time
start_time = time.time()

k = 0
step = 33
tot_len = 800
for i in range(1000000):
    a = tr_normalized[circular_index(tr_normalized, k, (k+step)%tot_len)][:,:10]
    k = (k+step)%tot_len

print("--- %s seconds ---" % (time.time() - start_time))

start_time = time.time()
for i in range(1000000):
    high = max(k+step, (k+step)%tot_len)
    a = tr_normalized[k:high,:10]
    k = (k+step)%tot_len

print("--- %s seconds ---" % (time.time() - start_time))

NameError: name 'circular_index' is not defined

In [ ]:
tr_normalized[:10, :3]

array([[-0.93011778,  0.92133772, -0.79851704],
       [-0.91383339, -0.2076762 , -0.79625988],
       [ 1.42879961,  0.59610576,  1.52729308],
       [ 1.24262993, -1.31099144, -0.04529711],
       [ 1.27240377, -1.33960823,  0.96323563],
       [ 1.42583762,  0.85067755,  1.27668474],
       [-0.94887093,  0.85024236, -0.7990482 ],
       [-0.84677264, -1.19199602, -0.73974572],
       [ 0.9008453 , -1.34720733,  1.12962203],
       [ 0.98870128, -1.33901788,  1.51646761]])

In [ ]:
myNN.predict(tr_normalized[:10, :10])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 10)

In [ ]:
a = np.array([1,2,3,4]*5)
a = a.reshape(5,4)
print(a)
print(a.shape)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
(5, 4)


In [ ]:
np.broadcast_to(a[0],(b.shape))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
b = np.array(('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'l', 'm', 'n'), dtype=object)
b = b.reshape(3,4)
print(b)
print(b.shape)

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']
 ['i' 'l' 'm' 'n']]
(3, 4)


In [ ]:
for row in range(a.shape[0]):
    c = np.broadcast_to(a[row],(b.shape))
    
    c = np.multiply(c, b)
    c = np.sum(c, axis=1)
    print(c)
    print('----------------------------------')

['abbcccdddd' 'effggghhhh' 'illmmmnnnn']
----------------------------------
['abbcccdddd' 'effggghhhh' 'illmmmnnnn']
----------------------------------
['abbcccdddd' 'effggghhhh' 'illmmmnnnn']
----------------------------------
['abbcccdddd' 'effggghhhh' 'illmmmnnnn']
----------------------------------
['abbcccdddd' 'effggghhhh' 'illmmmnnnn']
----------------------------------
